name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10.12]  # Versão correta do Python

    steps:
    - uses: actions/checkout@v3  # Atualizando para a versão que usa Node.js 20
    - name: Set up Python
      uses: actions/setup-python@v4  # Atualizando para a versão que usa Node.js 20
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -e .
        pip install pytest pytest-cov coveralls
    - name: Run tests
      run: |
        pytest --cov=./ --cov-report=xml
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.3.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
